name: build-release - $(SourceBranchName) - $(Date:yyyyMMdd)$(Rev:.r) -
pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - master
    exclude:
      - docs/*
      - LICENSE
      - README.md

variables:
  - group: aml-deployment-templates

stages:
  - stage: setup_infra
    displayName: Setup Infrastructure
    jobs:
      - template: ./templates/infra-build.yml
      - template: ./templates/infra-deploy.yml
        parameters:
          service_connection: ${{ variables.service_connection }}
          environment: ${{ variables.environment }}
          namespace: ${{ variables.namespace }}

  - stage: setup_data
    displayName: Setup Data
    dependsOn: setup_infra
    jobs:
      - deployment: Approval
        displayName: Setup Data Approval
        environment: $(environment)
      - template: ./templates/setup-data.yml
        parameters:
          service_connection: ${{ variables.service_connection }}
          environment: ${{ variables.environment }}
          namespace: ${{ variables.namespace }}
